amcl:
  ros__parameters:
    alpha1: 0.2    # rotation noise from rotation
    alpha2: 0.2    # rotation noise from translation
    alpha3: 0.2    # translation noise from translation
    alpha4: 0.2    # translation noise from rotation
    
    base_frame_id: "base_link"
    global_frame_id: "map"

    laser_likelihood_max_dist: 2.0
    laser_max_range: 3.5
    laser_min_range: 0.1
    laser_model_type: "likelihood_field"

    max_particles: 2000
    min_particles: 800

    odom_frame_id: "odom"

    recovery_alpha_fast: 0.1
    recovery_alpha_slow: 0.001
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"

    transform_tolerance: 0.5
    
    update_min_a: 0.2    # update when rotated 0.2 rad (~11 deg)
    update_min_d: 0.25   # update when moved 25cm

    z_hit: 0.9
    z_rand: 0.1